import { Anime } from "@/lib/types";

export const anime_data: Anime[] = [
  {
    "id": "bfa7bcb0-6c97-4423-a1bc-92f64cfaab7f",
    "title": "Attack on Titan",
    "release_date": "2013-04-07",
    "rating": 9.0,
    "genre": ["Action", "Drama", "Fantasy"],
    "type": "tv",
    "episodes": 87,
    "description": "\tEren Yeager once lived a peaceful life behind the towering walls that protected humanity from the terrifying Titans. But that peace was shattered when a massive Titan broke through the outer wall, destroying his home and taking his mother’s life. Determined to rid the world of these monsters, Eren joins the military alongside his friends to fight back.\n\tHowever, as the battles intensify and Eren uncovers hidden secrets about the Titans and the world, he begins to question who the real enemy is. With humanity’s survival hanging in the balance, Eren must confront betrayal, conspiracy, and his own inner demons as he fights to uncover the truth.",
    "studio": ["Wit Studio", "MAPPA"],
    "duration": 24,
    "status": "finished",
    "esrb": "M"
  },
  {
    "id": "49c02c34-2300-4f15-aea3-1a9475f0b4a9",
    "title": "Your Name",
    "release_date": "2016-08-26",
    "rating": 8.9,
    "genre": ["Romance", "Supernatural", "Drama"],
    "type": "movie",
    "episodes": 1,
    "description": "Two teenagers find themselves swapping bodies and must find a way to meet each other.",
    "studio": ["CoMix Wave Films"],
    "duration": 106,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "b2b0a62f-9fcb-4fa8-a07b-8b0f6b27e56a",
    "title": "My Hero Academia",
    "release_date": "2016-04-03",
    "rating": 8.0,
    "genre": ["Action", "Comedy", "Superhero"],
    "type": "tv",
    "episodes": 138,
    "description": "In a world where nearly everyone has superpowers, one boy without powers strives to become a hero.",
    "studio": ["Bones"],
    "duration": 24,
    "status": "airing",
    "esrb": "T"
  },
  {
    "id": "d8a1f6f1-6e2b-42be-8c56-0edb20d3f19d",
    "title": "Spirited Away",
    "release_date": "2001-07-20",
    "rating": 8.6,
    "genre": ["Adventure", "Fantasy", "Supernatural"],
    "type": "movie",
    "episodes": 1,
    "description": "A young girl becomes trapped in a strange world of spirits and must find a way to escape.",
    "studio": ["Studio Ghibli"],
    "duration": 125,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "be215d92-1a8f-49e4-b926-58c1e6db7300",
    "title": "One Piece",
    "release_date": "1999-10-20",
    "rating": 8.7,
    "genre": ["Action", "Adventure", "Fantasy"],
    "type": "tv",
    "episodes": 1071,
    "description": "Monkey D. Luffy and his pirate crew search for the legendary One Piece treasure.",
    "studio": ["Toei Animation"],
    "duration": 24,
    "status": "airing",
    "esrb": "T"
  },
  {
    "id": "9d8c3c1e-3f9d-4375-ae43-8dbe658f37ad",
    "title": "Demon Slayer",
    "release_date": "2019-04-06",
    "rating": 8.7,
    "genre": ["Action", "Supernatural", "Historical"],
    "type": "tv",
    "episodes": 44,
    "description": "A young boy becomes a demon slayer to avenge his family and save his sister.",
    "studio": ["ufotable"],
    "duration": 24,
    "status": "airing",
    "esrb": "M"
  },
  {
    "id": "a6a755f2-0545-41be-92d8-92d3f056b39a",
    "title": "Cowboy Bebop",
    "release_date": "1998-04-03",
    "rating": 8.9,
    "genre": ["Action", "Sci-Fi", "Space"],
    "type": "tv",
    "episodes": 26,
    "description": "A group of bounty hunters travel through space, catching criminals and facing their pasts.",
    "studio": ["Sunrise"],
    "duration": 24,
    "status": "finished",
    "esrb": "M"
  },
  {
    "id": "b9fb13b9-f307-4908-a2b7-7b17440e7ef5",
    "title": "Neon Genesis Evangelion",
    "release_date": "1995-10-04",
    "rating": 8.5,
    "genre": ["Mecha", "Drama", "Psychological"],
    "type": "tv",
    "episodes": 26,
    "description": "Teenagers pilot giant robots to protect Earth from mysterious beings called Angels.",
    "studio": ["Gainax"],
    "duration": 24,
    "status": "finished",
    "esrb": "M"
  },
  {
    "id": "07b84e9d-54b2-42a5-b69d-9d37fdcb0de9",
    "title": "Fullmetal Alchemist: Brotherhood",
    "release_date": "2009-04-05",
    "rating": 9.1,
    "genre": ["Action", "Adventure", "Fantasy"],
    "type": "tv",
    "episodes": 64,
    "description": "Two brothers search for the Philosopher's Stone to restore their bodies after a failed alchemy experiment.",
    "studio": ["Bones"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "f8b60a33-f2b2-4707-8c63-7bb648149e4a",
    "title": "Naruto Shippuden",
    "release_date": "2007-02-15",
    "rating": 8.3,
    "genre": ["Action", "Adventure", "Martial Arts"],
    "type": "tv",
    "episodes": 500,
    "description": "Naruto Uzumaki continues his journey to become Hokage while protecting his village from various threats.",
    "studio": ["Studio Pierrot"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "a8c6b94d-e6e7-4d2b-b7c3-1fc9a29f3e1a",
    "title": "Death Note",
    "release_date": "2006-10-04",
    "rating": 9.0,
    "genre": ["Mystery", "Supernatural", "Thriller"],
    "type": "tv",
    "episodes": 37,
    "description": "A high school student finds a notebook that allows him to kill anyone by writing their name, sparking a deadly game of cat and mouse with a brilliant detective.",
    "studio": ["Madhouse"],
    "duration": 24,
    "status": "finished",
    "esrb": "M"
  },
  {
    "id": "b9e6b657-4d0c-4f8d-967d-837f9be0fa1b",
    "title": "Sword Art Online",
    "release_date": "2012-07-08",
    "rating": 7.6,
    "genre": ["Action", "Fantasy", "Sci-Fi"],
    "type": "tv",
    "episodes": 25,
    "description": "Thousands of players become trapped in a virtual MMORPG, and the only way to escape is by beating the game.",
    "studio": ["A-1 Pictures"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "d1e2c1aa-f412-44f5-b18a-90b495b0482c",
    "title": "Tokyo Ghoul",
    "release_date": "2014-07-04",
    "rating": 7.8,
    "genre": ["Action", "Horror", "Supernatural"],
    "type": "tv",
    "episodes": 12,
    "description": "A young man struggles to adjust to life after becoming a half-ghoul, a creature that feeds on human flesh.",
    "studio": ["Pierrot"],
    "duration": 24,
    "status": "finished",
    "esrb": "M"
  },
  {
    "id": "e6c7b942-7d54-41ba-9436-683928d85d12",
    "title": "Hunter x Hunter",
    "release_date": "2011-10-02",
    "rating": 9.1,
    "genre": ["Action", "Adventure", "Fantasy"],
    "type": "tv",
    "episodes": 148,
    "description": "A young boy embarks on an adventure to become a Hunter and find his missing father.",
    "studio": ["Madhouse"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "da4f9bde-540d-44b6-b0de-59dfd57b3d4e",
    "title": "Dragon Ball Z",
    "release_date": "1989-04-26",
    "rating": 8.7,
    "genre": ["Action", "Adventure", "Martial Arts"],
    "type": "tv",
    "episodes": 291,
    "description": "Goku and his friends defend Earth from powerful foes, including intergalactic warriors, androids, and mystical beings.",
    "studio": ["Toei Animation"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "fcb85fda-738c-4a87-91a8-e52c8c3fd67a",
    "title": "Bleach",
    "release_date": "2004-10-05",
    "rating": 8.0,
    "genre": ["Action", "Adventure", "Supernatural"],
    "type": "tv",
    "episodes": 366,
    "description": "Ichigo Kurosaki gains the abilities of a Soul Reaper and must defend humanity from evil spirits.",
    "studio": ["Pierrot"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "a17e73dc-4e2b-478b-a79e-bfb0a09c73b4",
    "title": "Fairy Tail",
    "release_date": "2009-10-12",
    "rating": 7.7,
    "genre": ["Action", "Adventure", "Fantasy"],
    "type": "tv",
    "episodes": 328,
    "description": "Natsu Dragneel and his friends from the Fairy Tail guild take on various challenges to protect their world.",
    "studio": ["A-1 Pictures", "Satelight"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "f3dbb167-b6c3-4cd7-b9c5-6733c36fc03b",
    "title": "Black Clover",
    "release_date": "2017-10-03",
    "rating": 8.1,
    "genre": ["Action", "Fantasy", "Magic"],
    "type": "tv",
    "episodes": 170,
    "description": "Asta, a boy born without magic in a world where magic is everything, aims to become the Wizard King.",
    "studio": ["Pierrot"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
    "id": "a7b6e4cb-4495-4b78-9e76-80e9fc17355b",
    "title": "Fate/Zero",
    "release_date": "2011-10-02",
    "rating": 8.4,
    "genre": ["Action", "Supernatural", "Fantasy"],
    "type": "tv",
    "episodes": 25,
    "description": "Seven mages summon heroic spirits to battle for the Holy Grail, a mystical artifact said to grant any wish.",
    "studio": ["ufotable"],
    "duration": 24,
    "status": "finished",
    "esrb": "M"
  },
  {
    "id": "8cb25d39-c83a-471a-a4ae-504bb264b362",
    "title": "Clannad: After Story",
    "release_date": "2008-10-03",
    "rating": 9.1,
    "genre": ["Drama", "Romance", "Slice of Life"],
    "type": "tv",
    "episodes": 24,
    "description": "A continuation of the emotional journey of Tomoya and Nagisa as they face the challenges of adulthood.",
    "studio": ["Kyoto Animation"],
    "duration": 24,
    "status": "finished",
    "esrb": "T"
  },
  {
   "id": "08b84e9d-54b2-42a5-b69d-9d37fdcb0d10",
    "title": "Sakamoto Days",
    "release_date": "2025-01-01",
    "rating": 0,
    "genre": ["Action", "Comedy", "Adventure", "Martial Arts"],
    "type": "tv",
    "episodes": 0,
    "description": "Once feared as the most dangerous hitman, Taro Sakamoto has traded his violent life for that of a peaceful convenience store owner, married to the love of his life. But when old enemies resurface and threaten his new way of life, Sakamoto has no choice but to return to the world of assassins, only this time he is balancing his duties as a husband and father. 'Sakamoto Days' is a thrilling, yet comedic, tale of an unassuming man caught between the mundane and the deadly.",
    "studio": ["TMS Entertainment"],
    "duration": 24,
    "status": "announced",
    "esrb": "M"
  }
];
